# This is a basic workflow that is manually triggered
name: Versioning

on:
  push:
    branches:
      - develop
      - main

jobs:
  versioning:
    permissions:
      contents: write
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Generate Changelog
        run: npx conventional-changelog-cli -p angular -i CHANGELOG.md -s -r 0

      - name: Commit and push changelog
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "chore: Update changelog"
          git push origin HEAD

      - name: Create Tag
        run: |
          git tag -a v${{ github.run_number }} -m "Version ${{ github.run_number }}"
          git push origin v${{ github.run_number }}

